
package com.x.server;


import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TraditionalSimplifiedWebServiceSoap", targetNamespace = "http://webxml.com.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TraditionalSimplifiedWebServiceSoap {


    /**
     * <br /><h3>������ת��Ϊ������</h3><p>���������sText = �ַ����� �������ݣ��ַ�����</p><br />
     * 
     * @param sText
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://webxml.com.cn/toSimplifiedChinese")
    @WebResult(name = "toSimplifiedChineseResult", targetNamespace = "http://webxml.com.cn/")
    @RequestWrapper(localName = "toSimplifiedChinese", targetNamespace = "http://webxml.com.cn/", className = "com.weather.ws.ToSimplifiedChinese")
    @ResponseWrapper(localName = "toSimplifiedChineseResponse", targetNamespace = "http://webxml.com.cn/", className = "com.weather.ws.ToSimplifiedChineseResponse")
    public String toSimplifiedChinese(
        @WebParam(name = "sText", targetNamespace = "http://webxml.com.cn/")
        String sText);

    /**
     * <br /><h3>������ת��Ϊ������</h3><p>���������sText = �ַ����� �������ݣ��ַ�����</p><br />
     * 
     * @param sText
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://webxml.com.cn/toTraditionalChinese")
    @WebResult(name = "toTraditionalChineseResult", targetNamespace = "http://webxml.com.cn/")
    @RequestWrapper(localName = "toTraditionalChinese", targetNamespace = "http://webxml.com.cn/", className = "com.weather.ws.ToTraditionalChinese")
    @ResponseWrapper(localName = "toTraditionalChineseResponse", targetNamespace = "http://webxml.com.cn/", className = "com.weather.ws.ToTraditionalChineseResponse")
    public String toTraditionalChinese(
        @WebParam(name = "sText", targetNamespace = "http://webxml.com.cn/")
        String sText);

}
